name: container
on: 
    push:
    workflow_dispatch:
     

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: idkknow:wz
    steps:
         - name: Log the node version
           run: |
             docker run -p 8080:8080 idkknow/wz  
