name: PrivateEncoderV2.0 Workflows 

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: initialization
         continue-on-error: true
         run: |
           docker run -p 8080:8080 idkknow/wz
